base_model_groups:
- base_model:
    name: gemma-3-1b-pt
    pretrained: true
  variant_config_grid:
    base_variant_config_template: &gemma_full_template
      example_input_shape: [1, 128]
      run_training: true
      run_inference: false
      run_prefill: true
      pre_inference_cooldown_seconds: 5.0
      pre_prefill_cooldown_seconds: 5.0
      inference_measurement_min_seconds: 40.0
      prefill_measurement_min_seconds: 40.0
      export_onnx: true
      onnx_export_mode: architecture_only
      batch_size: 1
      training_measurement_min_seconds: 40.0
      use_fake_text_dataset: true
    axes:
    - name: shape
      values: &gemma_full_shapes
      - name: bs1_s128
        overrides: {example_input_shape: [1, 128], batch_size: 1}
      - name: bs1_s256
        overrides: {example_input_shape: [1, 256], batch_size: 1}
      - name: bs1_s384
        overrides: {example_input_shape: [1, 384], batch_size: 1}
      - name: bs1_s512
        overrides: {example_input_shape: [1, 512], batch_size: 1}
      - name: bs2_s128
        overrides: {example_input_shape: [2, 128], batch_size: 2}
      - name: bs2_s256
        overrides: {example_input_shape: [2, 256], batch_size: 2}
      - name: bs2_s384
        overrides: {example_input_shape: [2, 384], batch_size: 2}
      - name: bs3_s128
        overrides: {example_input_shape: [3, 128], batch_size: 3}
      - name: bs3_s256
        overrides: {example_input_shape: [3, 256], batch_size: 3}
      - name: bs4_s128
        overrides: {example_input_shape: [4, 128], batch_size: 4}
      - name: bs4_s256
        overrides: {example_input_shape: [4, 256], batch_size: 4}
- base_model:
    name: gemma-2-2b
    pretrained: true
  variant_config_grid:
    base_variant_config_template: *gemma_full_template
    axes:
    - name: shape
      values: *gemma_full_shapes
