defaults:
  prometheus_url: "http://192.168.5.60:31110"
  namespace: "crater-workspace"
  cpu_rate_window: "2m"
  query_step_seconds: 1

targets:
  bert_large:
    enabled: true
    result_json: "../../res/bert_large/results/bert_large_variants_v100_1774963594_results.json"
    node_name: "dell-67"
    pod_name: "sg-wangjh-260331-bbed6-default0-0"
