defaults:
  prometheus_url: "http://192.168.5.60:31110"
  namespace: "crater-workspace"
  cpu_rate_window: "22s"
  query_step_seconds: 1
  memory_baseline_window_seconds: 5

targets:
  vit:
    enabled: true
    result_json: res/vit/results/vit_variants_a100_1780456809_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-b7a24-default0-0
    gpu_id: "2"
    output_csv: csv/a100/vit_monitor.csv

  vgg11: #TODO
    enabled: true
    result_json: res/vgg11/results/vgg11_variants_a100_1780456835_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-4ae01-default0-0
    gpu_id: "0"
    output_csv: csv/a100/vgg11_monitor.csv

  resnet101:
    enabled: true
    result_json: res/resnet101/results/resnet101_variants_a100_1780456961_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-3ba16-default0-0
    gpu_id: "3"
    output_csv: csv/a100/resnet101_monitor.csv

  resnet50:
    enabled: true
    result_json: res/resnet50/results/resnet50_variants_a100_1780459422_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-69e76-default0-0
    gpu_id: "1"
    output_csv: csv/a100/resnet50_monitor.csv

  mobilenet:
    enabled: true
    result_json: res/mobilenet/results/mobilenet_variants_a100_1780469629_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-12436-default0-0
    gpu_id: "2"
    output_csv: "csv/a100/mobilenet_monitor.csv"

  vgg16:
    enabled: true
    result_json: res/vgg16/results/vgg16_variants_a100_1780469735_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-f0a19-default0-0
    gpu_id: "1"
    output_csv: "csv/a100/vgg16_monitor.csv"

  convnext:
    enabled: true
    result_json: res/convnext/results/convnext_variants_a100_1780479205_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-1b51f-default0-0
    gpu_id: "3"
    output_csv: "csv/a100/convnext_monitor.csv"

  vgg19:
    enabled: true
    result_json: res/vgg19/results/vgg19_variants_a100_1780485630_results.json
    node_name: xfusion-3
    pod_name: sg-wangjh-260603-71638-default0-0
    gpu_id: "1"
    output_csv: csv/a100/vgg19_monitor.csv

  resnet:
    enabled: true
    result_json: res/resnet/results/resnet_variants_a100_1780491584_results.json
    node_name: xfusion-2
    pod_name: sg-wangjh-260603-8c3a8-default0-0
    gpu_id: "0"
    output_csv: "csv/a100/resnet_monitor.csv"

  resnet152:
    enabled: true
    result_json: res/resnet152/results/resnet152_variants_a100_1780491443_results.json
    node_name: xfusion-3
    pod_name: sg-wangjh-260603-4f5f0-default0-0
    gpu_id: "0"
    output_csv: csv/a100/resnet152_monitor.csv

  yolov8: # TODO 采集时系统错误，正在重新采集
    enabled: false
    result_json: res/yolov8/results/yolov8_variants_a100_1780766745_results.json
    node_name: inspur-gpu-04
    pod_name: "sg-wangjh-260607-32362-default0-0"
    gpu_id: "3"
    output_csv: "csv/a100/yolov8_monitor.csv"

  bert:
    enabled: true
    result_json: res/bert/results/bert_variants_a100_1780491585_results.json
    node_name: xfusion-2
    pod_name: sg-wangjh-260603-59e05-default0-0
    gpu_id: "1"
    output_csv: csv/a100/bert_monitor.csv

  bert_large:
    enabled: true
    result_json: res/bert_large/results/bert_large_variants_a100_1780497896_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260603-27d2e-default0-0
    gpu_id: "2"
    output_csv: csv/a100/bert_large_monitor.csv

  beit:
    enabled: true
    result_json: res/beit/results/beit_variants_a100_1780541906_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260604-7c901-default0-0
    gpu_id: "0"
    output_csv: "csv/a100/beit_monitor.csv"

  densenet:
    enabled: true
    result_json: res/densenet/results/densenet_variants_a100_1780541906_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260604-f8658-default0-0
    gpu_id: "3"
    output_csv: "csv/a100/densenet_monitor.csv"

  yolov5:
    enabled: true
    result_json: res/yolov5/results/yolov5_variants_a100_1780987336_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260609-6f7b8-default0-0
    gpu_id: "0"
    output_csv: "csv/a100/yolov5_monitor.csv"

  yolov9:
    enabled: true
    result_json: res/yolov9/results/yolov9_variants_a100_1780542149_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260604-8adf2-default0-0
    gpu_id: "1"
    output_csv: "csv/a100/yolov9_monitor.csv"

  yolov11: # TODO 采集时系统错误，正在重新采集
    enabled: false
    result_json: res/yolov11/results/yolov11_variants_a100_1780563409_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260604-56f12-default0-0
    gpu_id: "1"
    output_csv: "csv/a100/yolov11_monitor.csv"
    
  efficientnet:
    enabled: true
    result_json: res/efficientnet/results/efficientnet_variants_a100_1780542052_results.json
    node_name: inspur-gpu-04
    pod_name: sg-wangjh-260604-aef4c-default0-0
    gpu_id: "2"
    output_csv: "csv/a100/efficientnet_monitor.csv"

  inception:
    enabled: false
    result_json: res/inception_v3/results/inception_v3_variants_v100_1779260815_results.json
    node_name: dell-68
    pod_name: sg-wangjh-260520-bde88-default0-0
    gpu_id: "0"
    output_csv: "csv/inception_monitor.csv"
    
  swin:
    enabled: true
    result_json: res/swin/results/swin_variants_a100_1780542313_results.json
    node_name: xfusion-2
    pod_name: sg-wangjh-260604-b982f-default0-0
    gpu_id: "1"
    output_csv: "csv/a100/swin_monitor.csv"

  gpt2:
    enabled: true
    result_json: res/gpt2/results/gpt2_variants_a100_1780563172_results.json
    node_name: xfusion-3
    pod_name: sg-wangjh-260604-c5d98-default0-0
    gpu_id: "1"
    output_csv: "csv/a100/gpt2_monitor.csv"
  
  t5:
    enabled: true
    result_json: res/t5/results/t5_variants_a100_1780563171_results.json
    node_name: xfusion-2
    pod_name: sg-wangjh-260604-bab36-default0-0
    gpu_id: "0"
    output_csv: "csv/a100/t5_monitor.csv"
  
  qwen3:
    enabled: true
    result_json: res/qwen3/results/qwen3_variants_a100_1781074513_results.json
    node_name: xfusion-3
    pod_name: sg-wangjh-260610-67343-default0-0
    gpu_id: "0"
    output_csv: "csv/a100/qwen3_monitor.csv"
